apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cj-example
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cjcontainer
            image: docker/whalesay
            command: ["cowsay","This is a cronjob!"]    