apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay
spec:
  template:
    spec:
      containers:
      - name: container1
        image: docker/whalesay
        command: ["cowsay","This is Kubernetes job!"]
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 60 
