kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: my-replica-set
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - rsexample
  template:
    metadata:
      labels:
        app: rsexample
    spec:
      containers:
      - name: rscontainer
        image: aamirpinger/flag
        ports:
        - containerPort: 80
